# Generated by Django 5.2.3 on 2025-08-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runningmates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningmate',
            name='pace',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runningmate',
            name='scheduled_time',
            field=models.TimeField(),
        ),
    ]
