# Generated by Django 5.2.3 on 2025-08-20 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runningmates', '0003_runparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.CharField(max_length=100)),
                ('scheduled_time', models.TimeField()),
                ('target_pace', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('max_participants', models.PositiveIntegerField(default=4)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runningmates_led', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='runparticipant',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runningmates.rungroup'),
        ),
        migrations.DeleteModel(
            name='RunningMate',
        ),
    ]
