# Generated by Django 5.2.3 on 2025-08-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveIntegerField()),
                ('distance', models.PositiveIntegerField()),
                ('pace', models.PositiveSmallIntegerField()),
                ('kcal', models.PositiveIntegerField()),
                ('route', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
