# Generated by Django 5.2.3 on 2025-07-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='route',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
