# Generated by Django 5.2.3 on 2025-08-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='distance',
            new_name='distance_m',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='duration',
            new_name='duration_sec',
        ),
    ]
