# Generated by Django 5.2.3 on 2025-08-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_distance_record_distance_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='route',
            field=models.TextField(blank=True, null=True),
        ),
    ]
